var AWS_ACCESS_KEY_MCKINSEY = "***REMOVED***";
var AWS_SECRET_ACCESS_KEY = "slkdajflsadf";
var PWD_MCKINSEY = "askldfjlsadf";
var API_KEY = "sdfasdf";
var access_key_MCKINSEY = "sdfsdf";
var AWS_SECRET_ACCESS_KEY = "TestKeyPassPwd";
var DSA_PRIVATE_KEY = "sdkflasaskdjfhjksdhfkdsjf";

var AWS_SECRET_KEY = "TestKeyPassPwasdlfsdfasdfd";
var DSA_PRIVATE_KEY = "My Private Key is here";
var git_token = "$GIT_TOKEN";
var gpg_key = "***REMOVED***";
var key = "4dsf245dsf896ds8f59ds65f4fdf587F5ds8dsf95ds87f";
var ssh_key = "Y2QwMWU0ZWUtOWZkMy00YjIxLThkMmYtMmVkYWFhZTBhMDI2OjEwZmYxMTQ3LWY4ZTAtNDU3ZC05ZGRlLWZhMWMzN2E1MWRjMA==";
var ssh_key_MCKINSEY = "Y2QwMWU0ZWUtOWZkMy00YjIxLThkMmYtMmVkYWFhZTBhMDI2OjEwZmYxMTQ3LWY4ZTAtNDU3ZC05ZGRlLWZhMWMzN2E1MTyuMA==";
var openssh_private_key = "mytest";
var SUMMVED_Password = "Slsdfl";
var AKC_TOKEN_MCKINSEY = "sakdfjlsdf";
var summved_MCKINSEY = 'test';
var summved2 = "testing232183test";
var test_keys = 'jsabdsafdsfjkbdsakfsbdlf';
var har_har_mahadev = '***REMOVED***';
var har_har = '***REMOVED***';
var har_hars = '***REMOVED***';
var hars = '***REMOVED***';
var mahardev = '***REMOVED***';
var hars_hars = '***REMOVED***';
